
export const FETCH_EPISODE_LIST_REQUEST = 'FETCH_EPISODE_LIST_REQUEST';

export const FETCH_EPISODE_LIST_LOAD = 'FETCH_EPISODE_LIST_LOAD';

export const FETCH_EPISODE_LIST_ERROR = 'FETCH_EPISODE_LIST_ERROR';

export const SELECT_SEASON = 'SELECT_SEASON';
